// Next.js API route support: https://nextjs.org/docs/api-routes/introduction

export default function handler(req, res) {
  res.status(200).json([
    {
      id: 1,
      title: "Le cheval Barbe",
      body: "\nAutrefois appelé cheval de barbarie par les romains, le barbe est un cheval de selle originaire d'Afrique du Nord, plus précisément du Maghreb. Cette race est souvent associée au berbère.\n\nC’est un cheval rude, très résistant, et proche de l’homme, il a longtemps été utilisé comme un cheval de guerre au Maghreb, mais aussi en Italie, en Espagne et en France. Un célèbre dicton dit sur lui :\n\n>“Qu'il peut la faim, il peut la soif, il peut le froid, il peut le chaud, jamais il n’est fatigué”\n\nSa première introduction en Europe fut pendant les conquêtes musulmanes, il sera plus tard importé en Europe comme monture de luxe ou reproducteurs d’élite. Le barbe était une monture royale, le roi Louis XIII fait son éducation équestre sur un cheval barbe appelé « Le Bonite ».\n\n\nAujourd’hui en Algérie, il est utilisé par la Garde Républicaine. Il est également utilisé lors des fantasias, tradition célèbre au Maghreb, qui consiste a simulé des assauts de guerre.\n\n\nLe cheval barbe était importé en Europe comme monture de luxe. Le future roi Louis XIII fait son éducation équestre sur un cheval barbe appeler « Le Bonite »\n\n\nLe barbe a influencé de nombreuse dans le monde comme le pure race Espagnol et le Mustang.",
      resumer:
        "Autrefois appelé cheval de barbarie par les romains, le barbe est un cheval de selle originaire d'Afrique du Nord, plus précisément du Maghreb. Cette race est souvent associée au berbère.\nC’est un cheval rude",
      img: "/article/cheval-barbe.jpg",
      alt: "Cheval barbe",
      categorie: "Culture",
      wilaya: null,
      dinastie: null,
      epoque: null,
      link: "cheval-barbe",
      date: "05/01/2022",
      contributeur: "Ketami",
      img_profil: "",
      local: "fr",
    },
    {
      id: 2,
      title: "Caftan El-Kadi",
      body: "Caftan El-Kadi littéralement caftan du juge est une tenue traditionnelle algérienne de Constantine. Initialement, c'était une tenue portée par les juges du royaume d’Alger, mais elle était aussi portée par les hauts fonctionnaires comme les aghas ou les bachaga. La tenu est par la suite était introduite dans le style vestimentaire féminin, aujourd’hui elle est portée principalement par les femmes.\n\n\nCe caftan est fait de velours et de broderie d’or constantinoise, la broderie est faite selon une technique algérienne connue sous le nom de Mejboud.\n\n\nLes motifs bordés rappellent la nature, ce sont souvent des feuilles, des fleurs, des branches ou des animaux. Il est également brodé avec une autre technique, la fetla. Le motif le plus brodé sur ce caftan est le paon d’or, c’est un motif typiquement Algérien, et plus précisément de la région de Constantine .\n\n\nLe caftan sera introduit dans le sultanat de Fès en 1830 par les Algériens fuyant la colonisation, les artisans de Fès l’appelleront « caftan b tarz dziri », ce qui se traduit en « caftan à la broderie algérienne. »",
      resumer:
        "Caftan El-Kadi littéralement caftan du juge est une tenue traditionnelle algérienne de Constantine. Initialement, c'était une tenue portée par les juges du royaume d’Alger, mais elle était aussi portée par les hauts fonctionnaires comme les aghas ou les bachaga. Le tenu est par la suite était introduite dans le style vestimentaire féminin, aujourd’hui, il est porté principalement par les femmes.",
      img: "/article/caftan-el-kadi.jpg",
      alt: "Caftan El-Kadi",
      categorie: "Culture",
      wilaya: "Constantine",
      dinastie: "Royaume d'Alger",
      epoque: "1600",
      link: "caftan-el-kadi",
      date: "06/01/2022",
      contributeur: "Ketami",
      img_profil: "",
      local: "fr",
    },
    {
      id: 3,
      title: "Bologhine Ibn Ziri, le fondateur d'Alger",
      body: "Bologhine Ibn Ziri est le fondateur (972) et un Émir de la dynastie des Zirides, il est le fils de Menad Ibn ziri, il est également le frère de Zawi Ibn Ziri le fondateur de la dynastie Ziride de Grenade (la taïfa de Grenade).\n\nLes Zirides sont une dynastie Sanhadja issu du Maghreb central, L’Algérie actuel. Ils règnent périodiquement sur tout le Maghreb et sur la taïfa de Grenade en Andalousie. Leur première capitale était Achir une ancienne ville qui se trouve dans l’actuel Kef Lakhdar dans la Wilaya de Médéa.\n\n\n## Le fondateur de la ville d’Alger\n\nEn 960 Bologhine Ibn Ziri fonde la ville d’Alger sur les ruines de l’ancienne ville romaine Icosium, sous le nom de Djezaïr Beni Mezghenna, il est donc le bâtisseur de la Casbah d’Alger. La ville devient importante pendant la période ottomane, elle donne son nom à la régence d’Alger, aussi appelé royaume d’Alger.\n\nMalgré plusieurs tentatives Européennes d’envahir la ville, notamment en 1541 avec l'expédition espagnole menais par Charles Quint ou encore en 1620 par une flotte britannique menée par l’amiral Robert Mansell, Alger est resté imprenable ce qui le vaut le surnom d'El Mahroussa («la bien-gardée»). Aujourd'hui, Alger est la capitale de l'Algérie.\n\n\nIl fonde aussi les villes de Médéa et Miliana, il fait aussi reconstruire plusieurs villages détruits par diverse révolte. Bologhine meurt en 984, son fils Al-Mansur lui succède.",
      resumer:
        "Bologhine Ibn Ziri est le fondateur (972) et un Émir de la dynastie des Zirides, il est le fils de Menad Ibn ziri, il est également le frère de Zawi Ibn Ziri le fondateur de la dynastie Ziride de Grenade (la taïfa de Grenade). Les Zirides sont une dynastie Sanhadja issu du Maghreb central, L’Algérie actuel.",
      img: "/article/Bologhine_Benziri_Benmenad_(cropped).jpg",
      alt: "Bologhine Ibn Ziri",
      categorie: "Histoire",
      wilaya: "Alger",
      dinastie: "Zirides",
      epoque: 960,
      link: "bologhine-ibn-ziri",
      date: "10/02/2022",
      contributeur: "Ketami",
      img_profil: "",
      local: "fr",
    },
    {
      id: 4,
      title: "Le Karakou, une tenue raffinée des Algéroises",
      body: "Alger fut une ville cosmopolite qui a connu beaucoup d’influence, les Algérois connu pour leur raffinement et pour leur gout du luxe en su s’approprier ses influences en les faisant évoluer et en les adaptant au mode de vie d’Alger, a l’image du karakou.\n\n\n## L’évolution du karakou\n\nLe Karakou est l'évolution de La ghlila, une ancienne tenue algérienne aux origines levantine et ottomane, il a eu aussi des influences berbères-andalouse. La ghlila était fait de soie, de brocart ou de velours brodé, mais contrairement au Karakou, la ghlila avait un grand décolleté décoré de boutons d'or ou d'argent, laissant apparaître une chemise blanche et sa longueur arrivait jusqu'aux cuisses. À l'arrivée du karakou, la ghlila devient un vêtement porté par les classes sociales inférieures.\n\n\n## Le karakou à travers le temps\n\nLe Karakou est une tenue traditionnelle algérienne, plus précisément d’Alger. Elle était initialement portée par les riches femmes d’Alger lors des différents événements comme les mariages ou encore les cérémonies de circoncisions.\n\n\nÀ l’origine cette tenue est une pièce unique, c'est-à-dire une veste en velours brodé en fils d’or réalisé par des artisans orfèvres. Tout comme le caftan, le karakou est brodé selon les techniques de broderie traditionnelle algérienne, appelée mejboud et fetla\n\n\nCette veste est traditionnellement associée avec un seroual chelka. Aujourd’hui cette veste a été modernisée et s’adapte très bien à la mode actuelle et est associée avec différent bas souvent moderne.",
      resumer:
        "Alger fut une ville cosmopolite qui a connu beaucoup d’influence, les Algérois connu pour leur raffinement et pour leur gout du luxe en su s’approprier ses influences en les faisant évoluer et en les adaptant au mode de vie d’Alger, a l’image du karakou.",
      img: "/article/Algerian_Karakou.jpg",
      alt: "Karakou",
      categorie: "Culture",
      wilaya: "Alger",
      dinastie: "Royaume d'Alger",
      epoque: 1830,
      date: "12/04/2022",
      link: "karakou",
      contributeur: "Ketami",
      img_profil: "",
      local: "fr",
    },
    {
      id: 5,
      title:
        "Les bijoux des Ath Yenni, un savoir-faire kabyle qui se transmet depuis des générations",
      body: "## Les Ath Yenni\n\nLes Ath Yenni sont initialement une tribu Kabyle, selon Ibn Khaldoun ils font partie de la confédération des Zouaoua, mais aujourd’hui elle est également une commune de Tizi Ouzou, composé de plusieurs localités celle-ci sont : Taourirt Mimoun (chef-lieu de la commune), Aṭ Lahcène, Aṭ Larbaâ, Taourirt L'Hadjadj, Tigzirt, M'Draa.\n\nCette tribu est connue pour son savoir-faire artisanal ancestral qu'ils transmettent depuis plusieurs générations, en effet en plus d'être d’anciens fabricants d'armes, principalement de fusils, ils sont aussi fabricant de poterie et de tapisserie, mais ils sont surtout connus pour leurs bijoux..\n\n\n## Les bijoux d’Ath Yenni\n\nLes bijoux kabyles sont un savoir-faire ancestral de la tribu des Ath Yenni, la transmission de ce savoir-faire est essentiellement familiale, transmis de père en fils, maintenant on retrouve aussi des femmes à qui ce savoir-faire a été transmis. Aujourd’hui, il existe des écoles pour apprendre la conception de ses bijoux, comme le CFPA Des arts (AT) Boukhalfa a Tizi Ouzou.\n\n\n## Fabrication\n\nCes bijoux sont faits d’argent avec un ornement en coraux. Ils sont essentiellement décorés avec les couleurs vertes, jaune, rouge et bleu, ses couleurs symbolise les éléments de la nature, c'est-à-dire jaune, soleil, le ciel, la terre et les plaines, ses quatre couleurs sont également les couleurs des étendards des rois de Numidie [1]. Les bijoux des Ath Yenni comme tout, ils n’ont pas échappé à la modernisation en effet les nouveaux artisans pour atteindre les nouvelles générations et continuer à faire vivre se savoir l’ont un peu modernisé en ajoutant de nouvelles couleurs telles que le turquoise, mais ses bijoux garde leur authenticité [2]. Les principaux bijoux fabriquer sont des bracelets, des ceintures, des boucles d’oreille, des diadèmes et des épingles.\n\n\nCes bijoux sont un accessoire essentiel dans la vie d’une femme kabyle, elle les porte dans la vie de tous les jours comme dans les différents événements important de sa vie comme par exemple son mariage.\n\n\nRenommé\n\nLeur succès dépasse cette tribu ou même la Kabylie, ces bijoux sont populaires dans toute l’Algérie, mais pas uniquement, puisqu'ils sont aussi populaires en Europe, notamment chez la diaspora algérienne et particulièrement dans la diaspora Kabyle.\n\n\nOn retrouve également de nombreux bijoux importer en France comme des trophées militaire ou par des ethnologues pour étudier les différentes ethnies en Algérie pendant la conquête française, ils sont aujourd’hui gardés au muséum d’Histoire naturelle de Toulouse [3], mais ils ne sont pas exposé pour différentes raison.\n\n",
      resumer:
        "Les Ath Yenni sont initialement une tribu Kabyle, selon Ibn Khaldoun ils font partie de la confédération des Zouaoua, mais aujourd’hui elle est également une commune de Tizi Ouzou, composé de plusieurs localités celle-ci sont : Taourirt Mimoun (chef-lieu de la commune), Aṭ Lahcène, Aṭ Larbaâ, Taourirt L'Hadjadj, Tigzirt, M'Draa.",
      img: "/article/bijoux-kabyles (1).png",
      alt: "Bijoux Kabyle",
      categorie: "Culture",
      wilaya: "Tizi ouzou",
      dinastie: "Algérie moderne",
      epoque: 1962,
      date: "12/05/2022",
      link: "bijoux-kabyle",
      contributeur: "ketami",
      img_profil: "",
      local: "fr",
    },
    {
      id: 6,
      title: "La blouza, une tenu qui a su conquérir le cœur des oranaise",
      body: "La blouza ou communément appelé la blouza oranaise est une tenue algérienne qui voit initialement le jour à Tlemcen au XXe siècle, cette robe est l’évolution de d’une autre tenu Algérienne, la robe abaya.\n\nCette robe a su se déplacer à travers les régions d’Algérie, et a su également évoluer, elle porte d’autre nom dans les autres wilayas comme “Gendoura” (littéralement “la robe”) a Constantine, “binouar” a Sétif ou encore “blouza Naïli” dans les hauts plateaux.\n\n\nToutes ses régions ont su s’approprier cette robe grâce à leurs évolutions.\n\n\n## La conception de la blouza\n\nCette tenue arrive dans la ville d’Oran grâce au couturier de Tlemcen qui ont émigré vers cette ville en apportant avec eux leur savoir-faire. Cette tenue est une longue robe sans manche cousu dans différente matière, on trouve essentiellement les matières suivantes : la soie, le velours, le coton, le nylon et la dentelle [1]. Cette robe grâce aux différents influence d’Oran elle a eu plusieurs modifications, et c’est dans cette ville qu’elle a été moderniser.\n\n\nAujourd'hui la blouza moderne est très populaire en Algérie et c’est propagé dans toutes les régions, mais c’est à Oran ou naturellement elle est particulièrement la plus apprécier.",
      resumer:
        "La blouza ou communément appelé la blouza oranaise est une tenue algérienne qui voit initialement le jour à Tlemcen au XXe siècle, cette robe est l’évolution de d’une autre tenu Algérienne, la robe abaya.",
      img: "/article/Blousa.jpg",
      alt: "la-blouza",
      categorie: "Culture",
      wilaya: "Oran",
      dinastie: "Algérie moderne",
      epoque: 1900,
      link: "la-blouza",
      date: "12/07/2022",
      contributeur: "Ketami",
      img_profil: "",
      local: "fr",
    },
    {
      id: 7,
      title:
        "Laalam, un village à la nature sauvage qui attire les touristes algériens",
      body: "<p class='firstP'>Laâlam est un petit village méconnu qui se trouve au pied de Tababort entre Béjaïa, Jijel et Sétif.</p> <p> Ce petit village compte environ trois mille habitants, on y parle Tasaḥlit, une langue qui provient de la langue Kutama, ce dialecte est également parlé à Melbou, Aokas, Souk El Ténine, Kherrata, on trouve aussi des locuteurs de ce dialecte dans les wilayas voisines tel que Jijel et Sétif. Le territoire où se trouvent ces locuteurs correspond historiquement à certaine fraction de la tribu des Kutuma. Les Ait Laâlam préfèrent appeler cette langue talaâlammite.<p> <h2> Histoire </h2> <p>Tababort fait partie de la chaine montagneuse des Babors, le toponyme de Babors existe depuis la période romaine, qui était connue sous le nom des Bavare, ou des Babare. Les Bavare sont une ancienne confédération des Babors, cette confédération est notamment connue pour s’être allié avec deux autres tribus Kabyles, les Quinquegentiens et les Fraxinenses contre l’empire romain.</p> <h2> Carte des tribus kabyles antique </h2> <img class='img-article-2' src='/article/laalam/tribu.png'> <br/> <div class='credit'>Crédit image : <a  href='journals.openedition.org'>journals.openedition.org</a></div> <br> <br> <p>Durant la colonisation française, le village de Laâlam n’était pas rattaché à la ville de Béjaïa, il faisait partie de la commune mixte de Tababort, cette commune faisait partie de ville de Djidjelli, l’actuel Jijel, bien qu’elle fît partie d’une commune mixte, la présence de colon était inexistante dans le village de Laâlam, c’est bien plus tard lors de la guerre d’Algérie que la première route vers ce village a été construite par l'armée française.</p> <p>Après l'indépendance, Tababort réintègre la ville de Béjaïa, plus tard le village de Laâlam ne sera plus rattacher à Tababort, mais a la commune de Tamridjet.</p> <p>En 2006, un événement dramatique secoue Laâlam, le 20 mars 2006, un violent séisme fait environ 4 morts et 78 blessés et une centaine de maisons détruites. Laâlam était presque méconnu par la majorité des Algériens avant ce drame.</p> <p>Aujourd'hui ce village, c'est remis de ses plaies, malgré un développement insuffisant, Laâlam attire de plus en plus de touriste, qui souhaite faire du tourisme d'aventure.  </p> <img class='laalam3' src='/article/laalam/laalam1.jpg'> <h2> Tourisme </h2> <p>Depuis quelques années, il y a un engouement autour de ce village, des touristes de toute l'Algérie viennent découvrir, la nature sauvage de Laâlam et de ses extraordinaires cascades qui rendent ce village unique. Cet été, des touristes d'Adrar ont visité ce village, ils étaient étonnés par la beauté des rivières et des cascades.</p> <h2> Agriculture </h2> <p>Comme la plupart des villages kabyles, Laâlam est un village agricole dont les terres cultivables sont ancestrales.</p> <p>Dans ce village, on y cultive un peu de tout, mais surtout des figues, des figues de barbarie, des courges, des haricots, néanmoins le produit phare qui est cultivé dans ce village, c'est la prune. On y cultive plusieurs variétés telles que notamment « la mirabelle » et « le santa-rosa ». Elles sont également cultivées dans ses différentes couleurs.</p>  <p>Chaque année, le village organise pendant l'été, la fête de la prune, pour mettre en avant les prunes du village et par extension tout le village.</p> <p>Malgré ce nouvel engouement, les nombreux touristes qui viennent visiter   le village et les efforts fournis par les Aït Laâlam, les habitants souhaitent avoir plus de moyen, notamment avec l'ouverture de nouvelle route qui leur faciliterait l'accès à l'éducation et à la santé, en effet l'ouverture de nouvelles routes telle que Melbou Laâlam leur permettra de réduire considérablement le temps du trajet entre les Hôpitaux, les lycées et les universités et le village, cette route leur permettra également développer le tourisme dans le village.</p>",
      resumer:
        "Laâlam est un petit village méconnu qui se trouve au pied de Tababort entre Béjaïa, Jijel et Sétif. Ce petit village compte environ trois mille habitants, on y parle Tasaḥlit, une langue qui provient de la langue Kutama, ",
      img: "/article/laalam/laalam5.jpg",
      alt: "laalam",
      categorie: "Culture",
      wilaya: "Bejaia",
      dinastie: "Algérie moderne",
      epoque: 2022,
      link: "laalam",
      contributeur: "Ketami",
      img_profil: "",
      local: "fr",
    },
  ]);
}
